default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['DB_DATABASE_NAME'] %>_development


test:
  <<: *default
  database: <%= ENV['DB_DATABASE_NAME'] %>_test

#
production:
  <<: *default
  database: <%= ENV['DB_DATABASE_NAME'] %>
